### ISSUE TITLE
有讨论群吗

### ISSUE THREAD

**Issue by lizhian** [KFCFans/OhMyScheduler#1]

**Comment by KFCFans** [comment]
目前为止没有。
我也在纠结要不要建个群方便大家交流。
目前没建主要是考虑到建了群以后一部分信息就封闭了，只有群内的人能看到。

我还是比较希望大家在Github上公开的交流～

治安 <notifications@github.com> 于2020年6月2日周二 上午11:34写道：

**Comment by KFCFans** [comment]
大家可以说说自己的看法，如果有必要，建一个讨论群也挺好的～
这样可以多多交流，有问题也能即使反馈。

**Comment by KFCFans** [comment]
您好，欢迎加入OhMyScheduler用户交流QQ群：487453839

二维码请见：https://www.yuque.com/ohmyscheduler/guidence/ztn4i5#NKVAa

v2.0.0目前已经发布，正式支持工作流任务编排，欢迎使用！
